<core::ptr::drop_in_place<inf_store::index::Index>>:
	push   %rbx
	mov    %rdi,%rbx
	mov    0x8(%rdi),%rsi
	test   %rsi,%rsi
	je     <core::ptr::drop_in_place<inf_store::index::Index>+OFF>
	mov    (%rbx),%rdi
	mov    $0x1,%edx
	call   <core::ptr::drop_in_place<inf_store::index::Index>+OFF>
	mov    0x18(%rbx),%rsi
	test   %rsi,%rsi
	je     <core::ptr::drop_in_place<inf_store::index::Index>+OFF>
	mov    0x10(%rbx),%rdi
	shl    $0x3,%rsi
	mov    $0x8,%edx
	pop    %rbx
	jmp   <core::ptr::drop_in_place<inf_store::index::Index>+OFF>
	pop    %rbx
	ret



<<inf_store::index::Index as core::fmt::Debug>::fmt>:
	push   %r15
	push   %r14
	push   %r12
	push   %rbx
	sub    $0x18,%rsp
	mov    %rdi,%rbx
	lea    0x0(%rip),%rdx        # <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	lea    0x8(%rsp),%r15
	mov    $0x5,%ecx
	mov    %r15,%rdi
	call   <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	lea    0x28(%rbx),%rcx
	lea    0x0(%rip),%rsi        # <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	lea    0x0(%rip),%r14        # <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	mov    0x0(%rip),%r12        # <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	mov    $0x4,%edx
	mov    %r15,%rdi
	mov    %r14,%r8
	call   *%r12
	lea    0x30(%rbx),%rcx
	lea    0x0(%rip),%rsi        # <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	mov    $0xa,%edx
	mov    %rax,%rdi
	mov    %r14,%r8
	call   *%r12
	add    $0x20,%rbx
	lea    0x0(%rip),%rsi        # <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	mov    $0x8,%edx
	mov    %rax,%rdi
	mov    %rbx,%rcx
	mov    %r14,%r8
	call   *%r12
	mov    %rax,%rdi
	call   <<inf_store::index::Index as core::fmt::Debug>::fmt+OFF>
	add    $0x18,%rsp
	pop    %rbx
	pop    %r12
	pop    %r14
	pop    %r15
	ret



<inf_store::index::Index::insert>:
	push   %rbx
	mov    0x20(%rdi),%r9
	shr    $0x4,%r9
	dec    %r9
	mov    0x8(%rdi),%r8
	mov    %rsi,%r10
	and    %r9,%r10
	mov    %r10,%rax
	shl    $0x4,%rax
	lea    0xf(%rax),%rcx
	cmp    %r8,%rcx
	jae    <inf_store::index::Index::insert+OFF>
	mov    (%rdi),%rcx
	mov    $0x1,%r11d
	nop
	movdqu (%rcx,%rax,1),%xmm0
	pmovmskb %xmm0,%ebx
	test   %ebx,%ebx
	jne    <inf_store::index::Index::insert+OFF>
	cmp    %r9,%r11
	ja     <inf_store::index::Index::insert+OFF>
	add    %r11,%r10
	and    %r9,%r10
	mov    %r10,%rax
	shl    $0x4,%rax
	lea    0xf(%rax),%rbx
	inc    %r11
	cmp    %r8,%rbx
	jb     <inf_store::index::Index::insert+OFF>
	lea    0x10(%rax),%rsi
	lea    0x0(%rip),%rcx        # <inf_store::index::Index::insert+OFF>
	mov    %rax,%rdi
	mov    %r8,%rdx
	call   <inf_store::index::Index::insert+OFF>
	tzcnt  %ebx,%r9d
	or     %r9,%rax
	cmp    %r8,%rax
	jae    <inf_store::index::Index::insert+OFF>
	cmpb   $0xfe,(%rcx,%rax,1)
	jne    <inf_store::index::Index::insert+OFF>
	decq   0x30(%rdi)
	mov    %rsi,%r8
	shr    $0x39,%r8
	mov    %r8b,(%rcx,%rax,1)
	mov    0x18(%rdi),%rcx
	cmp    %rcx,%rax
	jae    <inf_store::index::Index::insert+OFF>
	mov    0x10(%rdi),%rcx
	shl    $0x6,%rsi
	movabs $0x7fff000000000000,%r8
	and    %rsi,%r8
	movabs $0x8000000000000000,%rsi
	or     %rsi,%rdx
	or     %r8,%rdx
	mov    %rdx,(%rcx,%rax,8)
	incq   0x28(%rdi)
	pop    %rbx
	ret
	lea    0x0(%rip),%rdi        # <inf_store::index::Index::insert+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::index::Index::insert+OFF>
	mov    $0x5d,%esi
	call   <inf_store::index::Index::insert+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::index::Index::insert+OFF>
	mov    %rax,%rdi
	mov    %r8,%rsi
	call   <inf_store::index::Index::insert+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::index::Index::insert+OFF>
	mov    %rax,%rdi
	mov    %rcx,%rsi
	call   <.Llocal+OFF>



<inf_store::index::Index::live_from>:
	push   %rax
	cmpq   $0x0,0x28(%rdi)
	je     <inf_store::index::Index::live_from+OFF>
	mov    0x8(%rdi),%rdx
	mov    0x20(%rdi),%rcx
	dec    %rcx
	and    %rcx,%rsi
	cmp    %rdx,%rsi
	ja     <inf_store::index::Index::live_from+OFF>
	mov    (%rdi),%r9
	lea    (%r9,%rsi,1),%r8
	add    %r9,%rdx
	dec    %rsi
	xor    %eax,%eax
	mov    %r8,%r10
	jmp    <inf_store::index::Index::live_from+OFF>
	data16 data16 data16 cs nopw 0x0(%rax,%rax,1)
	lea    0x1(%r10),%r11
	inc    %rsi
	cmpb   $0x0,(%r10)
	mov    %r11,%r10
	jns    <inf_store::index::Index::live_from+OFF>
	test   %r10,%r10
	je     <inf_store::index::Index::live_from+OFF>
	cmp    %rdx,%r10
	jne    <inf_store::index::Index::live_from+OFF>
	cmp    %r8,%r9
	je     <inf_store::index::Index::live_from+OFF>
	mov    %r9,%r10
	inc    %r9
	xor    %r11d,%r11d
	inc    %rsi
	cmpb   $0x0,(%r10)
	mov    %r11,%r10
	js     <inf_store::index::Index::live_from+OFF>
	and    %rcx,%rsi
	mov    0x18(%rdi),%rax
	cmp    %rax,%rsi
	jae    <inf_store::index::Index::live_from+OFF>
	mov    0x10(%rdi),%rax
	movabs $0xffffffffffff,%rdx
	and    (%rax,%rsi,8),%rdx
	mov    $0x1,%eax
	pop    %rcx
	ret
	xor    %eax,%eax
	pop    %rcx
	ret
	lea    0x0(%rip),%rcx        # <inf_store::index::Index::live_from+OFF>
	mov    %rsi,%rdi
	mov    %rdx,%rsi
	call   <inf_store::index::Index::live_from+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::index::Index::live_from+OFF>
	mov    %rsi,%rdi
	mov    %rax,%rsi
	call   <.Llocal+OFF>



<inf_store::index::Index::position_of>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	push   %rax
	mov    %rdx,%rcx
	mov    %rdi,%rax
	mov    0x8(%rdi),%rdx
	mov    0x20(%rdi),%r9
	shr    $0x4,%r9
	dec    %r9
	mov    %rsi,%r10
	and    %r9,%r10
	mov    %r10,%rdi
	shl    $0x4,%rdi
	lea    0xf(%rdi),%r8
	cmp    %rdx,%r8
	jae    <inf_store::index::Index::position_of+OFF>
	shr    $0x39,%rsi
	mov    (%rax),%r11
	mov    0x10(%rax),%rbx
	movd   %esi,%xmm0
	punpcklbw %xmm0,%xmm0
	pshuflw $0x0,%xmm0,%xmm0
	pshufd $0x44,%xmm0,%xmm0
	mov    0x18(%rax),%rsi
	xor    %eax,%eax
	movdqa 0x0(%rip),%xmm1        # <inf_store::index::Index::position_of+OFF>
	movabs $0xffffffffffff,%r14
	xor    %r15d,%r15d
	movdqu (%r11,%rdi,1),%xmm2
	movdqa %xmm0,%xmm3
	pcmpeqb %xmm2,%xmm3
	pmovmskb %xmm3,%r12d
	data16 cs nopw 0x0(%rax,%rax,1)
	test   %r12w,%r12w
	je     <inf_store::index::Index::position_of+OFF>
	tzcnt  %r12d,%r8d
	or     %rdi,%r8
	cmp    %rsi,%r8
	jae    <inf_store::index::Index::position_of+OFF>
	lea    -0x1(%r12),%ebp
	and    %r12d,%ebp
	mov    (%rbx,%r8,8),%r13
	and    %r14,%r13
	mov    %ebp,%r12d
	cmp    %rcx,%r13
	jne    <inf_store::index::Index::position_of+OFF>
	jmp    <inf_store::index::Index::position_of+OFF>
	nopl   0x0(%rax)
	pcmpeqb %xmm1,%xmm2
	pmovmskb %xmm2,%edi
	test   %edi,%edi
	jne    <inf_store::index::Index::position_of+OFF>
	inc    %r15
	cmp    %r9,%r15
	ja     <inf_store::index::Index::position_of+OFF>
	add    %r15,%r10
	and    %r9,%r10
	mov    %r10,%rdi
	shl    $0x4,%rdi
	lea    0xf(%rdi),%r8
	cmp    %rdx,%r8
	jb     <inf_store::index::Index::position_of+OFF>
	lea    0x10(%rdi),%rsi
	lea    0x0(%rip),%rcx        # <inf_store::index::Index::position_of+OFF>
	call   <inf_store::index::Index::position_of+OFF>
	mov    $0x1,%eax
	mov    %r8,%rdx
	add    $0x8,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	jmp    <inf_store::index::Index::position_of+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::index::Index::position_of+OFF>
	mov    %r8,%rdi
	call   <.Llocal+OFF>



<inf_store::index::Index::remove>:
	push   %rbx
	mov    %rdi,%rbx
	call   <inf_store::index::Index::remove+OFF>
	cmp    $0x1,%rax
	jne    <inf_store::index::Index::remove+OFF>
	mov    %rdx,%rdi
	and    $0xfffffffffffffff0,%rdi
	mov    0x8(%rbx),%rax
	mov    %rdx,%rcx
	or     $0xf,%rcx
	cmp    %rax,%rcx
	jae    <inf_store::index::Index::remove+OFF>
	mov    (%rbx),%rax
	movdqu (%rax,%rdi,1),%xmm0
	pcmpeqb 0x0(%rip),%xmm0        # <inf_store::index::Index::remove+OFF>
	pmovmskb %xmm0,%ecx
	test   %ecx,%ecx
	je     <inf_store::index::Index::remove+OFF>
	movb   $0x80,(%rax,%rdx,1)
	mov    0x18(%rbx),%rsi
	cmp    %rsi,%rdx
	jae    <inf_store::index::Index::remove+OFF>
	mov    0x10(%rbx),%rax
	movq   $0x0,(%rax,%rdx,8)
	decq   0x28(%rbx)
	pop    %rbx
	ret
	movb   $0xfe,(%rax,%rdx,1)
	incq   0x30(%rbx)
	mov    0x18(%rbx),%rsi
	cmp    %rsi,%rdx
	jb     <inf_store::index::Index::remove+OFF>
	lea    0x0(%rip),%rax        # <inf_store::index::Index::remove+OFF>
	mov    %rdx,%rdi
	mov    %rax,%rdx
	call   <inf_store::index::Index::remove+OFF>
	lea    0x10(%rdi),%rsi
	lea    0x0(%rip),%rcx        # <inf_store::index::Index::remove+OFF>
	mov    %rax,%rdx
	call   <inf_store::index::Index::remove+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::index::Index::remove+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::index::Index::remove+OFF>
	mov    $0x15,%esi
	call   <.Llocal+OFF>



<inf_store::index::Index::replace>:
	push   %r15
	push   %r14
	push   %rbx
	mov    %rcx,%rbx
	mov    %rsi,%r14
	mov    %rdi,%r15
	call   <inf_store::index::Index::replace+OFF>
	cmp    $0x1,%rax
	jne    <inf_store::index::Index::replace+OFF>
	mov    0x18(%r15),%rsi
	cmp    %rsi,%rdx
	jae    <inf_store::index::Index::replace+OFF>
	mov    0x10(%r15),%rax
	shl    $0x6,%r14
	movabs $0x7fff000000000000,%rcx
	and    %r14,%rcx
	movabs $0x8000000000000000,%rsi
	or     %rsi,%rbx
	or     %rcx,%rbx
	mov    %rbx,(%rax,%rdx,8)
	pop    %rbx
	pop    %r14
	pop    %r15
	ret
	lea    0x0(%rip),%rdi        # <inf_store::index::Index::replace+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::index::Index::replace+OFF>
	mov    $0x16,%esi
	call   <inf_store::index::Index::replace+OFF>
	lea    0x0(%rip),%rax        # <inf_store::index::Index::replace+OFF>
	mov    %rdx,%rdi
	mov    %rax,%rdx
	call   <.Llocal+OFF>



<inf_store::index::Index::with_capacity>:
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	cmp    $0x1,%rsi
	adc    $0x0,%rsi
	imul   $0x64,%rsi,%rax
	movabs $0xc0c0c0c0c0c0c0c1,%rcx
	mul    %rcx
	shr    $0x6,%rdx
	movabs $0xd2d2d2d2d2d2d2d4,%rcx
	imul   %rsi,%rcx
	movabs $0x303030303030303,%rsi
	xor    %eax,%eax
	cmp    %rsi,%rcx
	seta   %al
	mov    %rdi,%rbx
	add    %rdx,%rax
	mov    $0x10,%r14d
	cmp    $0x2,%rax
	jb     <inf_store::index::Index::with_capacity+OFF>
	dec    %rax
	bsr    %rax,%rcx
	not    %ecx
	mov    $0xffffffffffffffff,%rax
	shr    %cl,%rax
	cmp    $0x10,%rax
	mov    $0xf,%r14d
	cmovae %rax,%r14
	inc    %r14
	call   <inf_store::index::Index::with_capacity+OFF>
	mov    $0x1,%esi
	mov    %r14,%rdi
	call   <inf_store::index::Index::with_capacity+OFF>
	test   %rax,%rax
	je     <inf_store::index::Index::with_capacity+OFF>
	mov    %rax,%r15
	mov    %rax,%rdi
	mov    $0x80,%esi
	mov    %r14,%rdx
	call   <inf_store::index::Index::with_capacity+OFF>
	lea    0x0(,%r14,8),%r12
	call   <inf_store::index::Index::with_capacity+OFF>
	mov    $0x8,%esi
	mov    %r12,%rdi
	call   <inf_store::index::Index::with_capacity+OFF>
	test   %rax,%rax
	je     <inf_store::index::Index::with_capacity+OFF>
	mov    %rax,%r13
	add    $0xfffffffffffffff8,%r12
	mov    %rax,%rdi
	xor    %esi,%esi
	mov    %r12,%rdx
	call   <inf_store::index::Index::with_capacity+OFF>
	movq   $0x0,-0x8(%r13,%r14,8)
	mov    %r15,(%rbx)
	mov    %r14,0x8(%rbx)
	mov    %r13,0x10(%rbx)
	mov    %r14,0x18(%rbx)
	mov    %r14,0x20(%rbx)
	xorps  %xmm0,%xmm0
	movups %xmm0,0x28(%rbx)
	mov    %rbx,%rax
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	ret
	mov    $0x1,%edi
	mov    %r14,%rsi
	call   <inf_store::index::Index::with_capacity+OFF>
	mov    $0x8,%edi
	mov    %r12,%rsi
	call   <inf_store::index::Index::with_capacity+OFF>
	ud2
	mov    %rax,%rbx
	mov    $0x1,%edx
	mov    %r15,%rdi
	mov    %r14,%rsi
	call   <inf_store::index::Index::with_capacity+OFF>
	mov    %rbx,%rdi
	call   <.Llocal+OFF>



<inf_store::store::CellStore::get>:
	push   %r15
	push   %r14
	push   %r12
	push   %rbx
	push   %rax
	mov    %rcx,%rbx
	mov    %rdx,%r14
	mov    %rsi,%r15
	mov    %rdi,%r12
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %rsi,%rdi
	mov    %r14,%rsi
	call   <inf_store::store::CellStore::get+OFF>
	mov    %r12,%rdi
	mov    %r15,%rsi
	mov    %r14,%rdx
	mov    %rax,%rcx
	mov    %rbx,%r8
	add    $0x8,%rsp
	pop    %rbx
	pop    %r12
	pop    %r14
	pop    %r15
	jmp   <.Llocal+OFF>



<inf_store::store::CellStore::getdel>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0x48,%rsp
	mov    %r8,%r15
	mov    %rcx,%rbp
	mov    %rdx,%r13
	mov    %rsi,%r14
	mov    %rdi,%rbx
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %r13,%rdi
	mov    %rcx,%rsi
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x28(%rsp),%rdi
	mov    %r14,%rsi
	mov    %r13,%rdx
	mov    %rbp,%rcx
	mov    %rax,%r8
	mov    %r15,%r9
	call   <inf_store::store::CellStore::getdel+OFF>
	cmpl   $0x1,0x28(%rsp)
	jne    <inf_store::store::CellStore::getdel+OFF>
	mov    0x30(%rsp),%r12
	mov    0x40(%r14),%rsi
	mov    %r12,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::getdel+OFF>
	mov    0x38(%rsp),%r15
	mov    0x38(%r14),%rax
	shl    $0x4,%rdi
	mov    %r12,0x20(%rsp)
	and    $0x1fffff,%r12d
	lea    (%r12,%r15,1),%rcx
	cmp    0x8(%rax,%rdi,1),%rcx
	ja     <inf_store::store::CellStore::getdel+OFF>
	mov    %rbx,0x18(%rsp)
	test   %r15,%r15
	je     <inf_store::store::CellStore::getdel+OFF>
	add    %rdi,%rax
	add    (%rax),%r12
	movzbl (%r12),%ecx
	mov    %ecx,%eax
	shr    $0x4,%eax
	cmp    $0x1,%eax
	je     <inf_store::store::CellStore::getdel+OFF>
	cmp    $0x2,%eax
	jne    <inf_store::store::CellStore::getdel+OFF>
	movabs $0x8000000000000000,%rax
	mov    0x18(%rsp),%rbx
	jmp    <inf_store::store::CellStore::getdel+OFF>
	movabs $0x8000000000000000,%rax
	mov    %rax,(%rbx)
	jmp    <inf_store::store::CellStore::getdel+OFF>
	mov    %ecx,(%rsp)
	cmp    $0x1,%r15
	je     <inf_store::store::CellStore::getdel+OFF>
	cmp    $0x4,%r15
	jbe    <inf_store::store::CellStore::getdel+OFF>
	movzbl (%rsp),%eax
	and    $0x1,%eax
	lea    (%rax,%rax,4),%rax
	movzbl 0x1(%r12),%ecx
	lea    (%rcx,%rax,1),%rdi
	add    $0x8,%rdi
	movzwl 0x2(%r12),%eax
	movzbl 0x4(%r12),%ebx
	shl    $0x10,%ebx
	or     %rax,%rbx
	lea    (%rdi,%rbx,1),%rsi
	cmp    %r15,%rsi
	ja     <inf_store::store::CellStore::getdel+OFF>
	test   %rbx,%rbx
	mov    %rbx,0x10(%rsp)
	je     <inf_store::store::CellStore::getdel+OFF>
	mov    %rdi,(%rsp)
	call   <inf_store::store::CellStore::getdel+OFF>
	mov    $0x1,%esi
	mov    %rbx,%rdi
	call   <inf_store::store::CellStore::getdel+OFF>
	test   %rax,%rax
	je     <inf_store::store::CellStore::getdel+OFF>
	mov    (%rsp),%rsi
	add    %r12,%rsi
	mov    %rax,0x8(%rsp)
	mov    %rax,%rdi
	mov    %rbx,%rdx
	call   <inf_store::store::CellStore::getdel+OFF>
	movzbl (%r12),%eax
	and    $0x1,%al
	mov    %eax,(%rsp)
	cmp    $0xc,%r15
	jbe    <inf_store::store::CellStore::getdel+OFF>
	jmp    <inf_store::store::CellStore::getdel+OFF>
	mov    (%rsp),%eax
	and    $0x1,%al
	mov    %eax,(%rsp)
	mov    $0x1,%eax
	mov    %rax,0x8(%rsp)
	cmp    $0xc,%r15
	ja     <inf_store::store::CellStore::getdel+OFF>
	cmpb   $0x0,(%rsp)
	jne    <inf_store::store::CellStore::getdel+OFF>
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %r13,%rdi
	mov    %rbp,%rsi
	call   <inf_store::store::CellStore::getdel+OFF>
	mov    0x20(%rsp),%rbx
	mov    %rax,%r12
	mov    0x38(%r14),%rsi
	mov    0x40(%r14),%rdx
	lea    0x28(%rsp),%rdi
	mov    %rbx,%rcx
	mov    %r15,%r8
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x2290(%r14),%rdi
	mov    %r12,%rsi
	mov    %rbx,%rdx
	call   <inf_store::store::CellStore::getdel+OFF>
	mov    %r14,%rdi
	mov    %rbx,%rsi
	mov    %r15,%rdx
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x80(%r14),%rdi
	lea    0x28(%rsp),%rsi
	call   <inf_store::store::CellStore::getdel+OFF>
	cmpb   $0x0,(%rsp)
	je     <inf_store::store::CellStore::getdel+OFF>
	mov    0x22e8(%r14),%rax
	cmp    $0x1,%rax
	adc    $0xffffffffffffffff,%rax
	mov    %rax,0x22e8(%r14)
	mov    0x18(%rsp),%rbx
	mov    0x10(%rsp),%rax
	mov    %rax,(%rbx)
	mov    0x8(%rsp),%rcx
	mov    %rcx,0x8(%rbx)
	mov    %rax,0x10(%rbx)
	mov    %rbx,%rax
	add    $0x48,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::getdel+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::getdel+OFF>
	mov    $0x10,%esi
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::getdel+OFF>
	mov    $0x2,%edi
	mov    $0x5,%esi
	mov    %r15,%rdx
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::getdel+OFF>
	mov    %r15,%rdx
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::getdel+OFF>
	mov    $0x8,%edi
	mov    $0xd,%esi
	mov    %r15,%rdx
	call   <inf_store::store::CellStore::getdel+OFF>
	ud2
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::getdel+OFF>
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::getdel+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <inf_store::store::CellStore::getdel+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::getdel+OFF>
	mov    $0x1,%edi
	mov    $0x1,%esi
	call   <inf_store::store::CellStore::getdel+OFF>
	mov    $0x1,%edi
	mov    %rbx,%rsi
	call   <inf_store::store::CellStore::getdel+OFF>
	mov    %rax,%rbx
	cmpl   $0x0,0x10(%rsp)
	je     <inf_store::store::CellStore::getdel+OFF>
	mov    $0x1,%edx
	mov    0x8(%rsp),%rdi
	mov    0x10(%rsp),%rsi
	call   <inf_store::store::CellStore::getdel+OFF>
	mov    %rbx,%rdi
	call   <.Lswitch.table._ZN9inf_store7catalog9NsCatalog6encode17hb15ce09b8ccb2dc1E+OFF>



<inf_store::store::CellStore::get_ex>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0x38,%rsp
	mov    %r9,%r15
	mov    %r8,0x18(%rsp)
	mov    %rcx,%r14
	mov    %rdx,%r12
	mov    %rsi,%r13
	mov    %rdi,%rbx
	mov    0x70(%rsp),%rbp
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %r12,%rdi
	mov    %rcx,%rsi
	call   <inf_store::store::CellStore::get_ex+OFF>
	lea    0x20(%rsp),%rdi
	mov    %r13,%rsi
	mov    %r12,%rdx
	mov    %r14,%rcx
	mov    %rax,%r8
	mov    %rbp,%r9
	call   <inf_store::store::CellStore::get_ex+OFF>
	cmpl   $0x1,0x20(%rsp)
	jne    <inf_store::store::CellStore::get_ex+OFF>
	mov    0x28(%rsp),%rbp
	mov    0x40(%r13),%rsi
	mov    %rbp,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::get_ex+OFF>
	mov    0x30(%rsp),%rdx
	mov    0x38(%r13),%rax
	shl    $0x4,%rdi
	and    $0x1fffff,%ebp
	lea    (%rdx,%rbp,1),%rcx
	cmp    0x8(%rax,%rdi,1),%rcx
	ja     <inf_store::store::CellStore::get_ex+OFF>
	test   %rdx,%rdx
	je     <inf_store::store::CellStore::get_ex+OFF>
	add    %rdi,%rax
	add    (%rax),%rbp
	movzbl 0x0(%rbp),%eax
	shr    $0x4,%eax
	cmp    $0x1,%eax
	je     <inf_store::store::CellStore::get_ex+OFF>
	cmp    $0x2,%eax
	je     <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x10,%esi
	call   <inf_store::store::CellStore::get_ex+OFF>
	incq   0x22d0(%r13)
	movabs $0x8000000000000000,%rax
	mov    %rax,(%rbx)
	jmp    <inf_store::store::CellStore::get_ex+OFF>
	incq   0x22c8(%r13)
	cmp    $0x1,%rdx
	je     <inf_store::store::CellStore::get_ex+OFF>
	cmp    $0x4,%rdx
	jbe    <inf_store::store::CellStore::get_ex+OFF>
	mov    %r15,0x10(%rsp)
	movzbl 0x0(%rbp),%eax
	and    $0x1,%eax
	lea    (%rax,%rax,4),%rax
	movzbl 0x1(%rbp),%ecx
	lea    (%rcx,%rax,1),%rdi
	add    $0x8,%rdi
	movzwl 0x2(%rbp),%eax
	movzbl 0x4(%rbp),%r15d
	shl    $0x10,%r15d
	or     %rax,%r15
	lea    (%rdi,%r15,1),%rsi
	cmp    %rdx,%rsi
	ja     <inf_store::store::CellStore::get_ex+OFF>
	test   %r15,%r15
	je     <inf_store::store::CellStore::get_ex+OFF>
	mov    %rdi,0x8(%rsp)
	call   <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x1,%esi
	mov    %r15,%rdi
	call   <inf_store::store::CellStore::get_ex+OFF>
	test   %rax,%rax
	je     <inf_store::store::CellStore::get_ex+OFF>
	add    0x8(%rsp),%rbp
	mov    %rax,%rdi
	mov    %rbp,%rsi
	mov    %r15,%rdx
	mov    %rax,%rbp
	call   <inf_store::store::CellStore::get_ex+OFF>
	mov    0x18(%rsp),%rax
	test   %rax,%rax
	mov    0x70(%rsp),%rdx
	jne    <inf_store::store::CellStore::get_ex+OFF>
	jmp    <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x1,%ebp
	mov    0x18(%rsp),%rax
	test   %rax,%rax
	mov    0x70(%rsp),%rdx
	je     <inf_store::store::CellStore::get_ex+OFF>
	cmp    $0x1,%rax
	jne    <inf_store::store::CellStore::get_ex+OFF>
	xor    %ecx,%ecx
	jmp    <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x1,%ecx
	mov    %rdx,(%rsp)
	mov    %r13,%rdi
	mov    %r12,%rsi
	mov    %r14,%rdx
	mov    0x10(%rsp),%r8
	xor    %r9d,%r9d
	call   <inf_store::store::CellStore::get_ex+OFF>
	mov    %r15,(%rbx)
	mov    %rbp,0x8(%rbx)
	mov    %r15,0x10(%rbx)
	mov    %rbx,%rax
	add    $0x38,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x2,%edi
	mov    $0x5,%esi
	call   <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_ex+OFF>
	call   <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_ex+OFF>
	call   <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_ex+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <inf_store::store::CellStore::get_ex+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x1,%edi
	mov    $0x1,%esi
	call   <inf_store::store::CellStore::get_ex+OFF>
	mov    $0x1,%edi
	mov    %r15,%rsi
	call   <inf_store::store::CellStore::get_ex+OFF>
	mov    %rax,%rbx
	test   %r15d,%r15d
	je     <inf_store::store::CellStore::get_ex+OFF>
	mov    %rbp,%rdi
	mov    $0x1,%edx
	mov    %r15,%rsi
	call   <inf_store::store::CellStore::get_ex+OFF>
	mov    %rbx,%rdi
	call   <.Llocal+OFF>



<inf_store::store::CellStore::get_range>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0x28,%rsp
	mov    %r9,0x8(%rsp)
	mov    %r8,%r15
	mov    %rcx,%r13
	mov    %rdx,%rbp
	mov    %rsi,%r12
	mov    %rdi,%rbx
	mov    0x60(%rsp),%r14
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %rbp,%rdi
	mov    %rcx,%rsi
	call   <inf_store::store::CellStore::get_range+OFF>
	lea    0x10(%rsp),%rdi
	mov    %r12,%rsi
	mov    %rbp,%rdx
	mov    %r13,%rcx
	mov    %rax,%r8
	mov    %r14,%r9
	call   <inf_store::store::CellStore::get_range+OFF>
	cmpl   $0x1,0x10(%rsp)
	jne    <inf_store::store::CellStore::get_range+OFF>
	mov    0x18(%rsp),%rax
	mov    0x20(%rsp),%rdx
	incq   0x22c8(%r12)
	mov    0x40(%r12),%rsi
	mov    %rax,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::get_range+OFF>
	mov    0x38(%r12),%rcx
	shl    $0x4,%rdi
	and    $0x1fffff,%eax
	lea    (%rax,%rdx,1),%rsi
	cmp    0x8(%rcx,%rdi,1),%rsi
	ja     <inf_store::store::CellStore::get_range+OFF>
	test   %rdx,%rdx
	je     <inf_store::store::CellStore::get_range+OFF>
	add    %rdi,%rcx
	add    (%rcx),%rax
	movzbl (%rax),%ecx
	mov    %ecx,%esi
	shr    $0x4,%esi
	cmp    $0x1,%esi
	je     <inf_store::store::CellStore::get_range+OFF>
	cmp    $0x2,%esi
	jne    <inf_store::store::CellStore::get_range+OFF>
	movb   $0x6,0x8(%rbx)
	movq   $0x0,(%rbx)
	jmp    <inf_store::store::CellStore::get_range+OFF>
	incq   0x22d0(%r12)
	movq   $0x1,(%rbx)
	movq   $0x0,0x8(%rbx)
	mov    %rbx,%rax
	add    $0x28,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	cmp    $0x1,%rdx
	je     <inf_store::store::CellStore::get_range+OFF>
	cmp    $0x4,%rdx
	jbe    <inf_store::store::CellStore::get_range+OFF>
	movzbl %cl,%ecx
	and    $0x1,%ecx
	lea    (%rcx,%rcx,4),%rcx
	movzbl 0x1(%rax),%esi
	lea    (%rsi,%rcx,1),%rdi
	add    $0x8,%rdi
	movzwl 0x2(%rax),%ecx
	movzbl 0x4(%rax),%r8d
	shl    $0x10,%r8d
	or     %rcx,%r8
	lea    (%rdi,%r8,1),%rsi
	cmp    %rdx,%rsi
	ja     <inf_store::store::CellStore::get_range+OFF>
	lea    (%r15,%r8,1),%rdx
	xor    %ecx,%ecx
	test   %rdx,%rdx
	cmovle %rcx,%rdx
	test   %r15,%r15
	cmovns %r15,%rdx
	mov    0x8(%rsp),%r9
	lea    (%r9,%r8,1),%rsi
	test   %rsi,%rsi
	cmovg  %rsi,%rcx
	test   %r9,%r9
	cmovns %r9,%rcx
	lea    -0x1(%r8),%rsi
	cmp    %rcx,%rsi
	cmovl  %rsi,%rcx
	cmp    %rcx,%rdx
	setg   %sil
	cmp    %r8,%rdx
	setae  %r8b
	or     %sil,%r8b
	jne    <inf_store::store::CellStore::get_range+OFF>
	add    %rdi,%rax
	sub    %rdx,%rcx
	inc    %rcx
	add    %rdx,%rax
	mov    %rax,(%rbx)
	mov    %rcx,0x8(%rbx)
	jmp    <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_range+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_range+OFF>
	mov    $0x10,%esi
	call   <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_range+OFF>
	mov    $0x2,%edi
	mov    $0x5,%esi
	call   <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_range+OFF>
	call   <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_range+OFF>
	call   <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_range+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <inf_store::store::CellStore::get_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_range+OFF>
	mov    $0x1,%edi
	mov    $0x1,%esi
	call   <.Llocal+OFF>



<inf_store::store::CellStore::get_str>:
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0x20,%rsp
	mov    %r8,%r15
	mov    %rcx,%r12
	mov    %rdx,%r13
	mov    %rsi,%r14
	mov    %rdi,%rbx
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %r13,%rdi
	mov    %rcx,%rsi
	call   <inf_store::store::CellStore::get_str+OFF>
	lea    0x8(%rsp),%rdi
	mov    %r14,%rsi
	mov    %r13,%rdx
	mov    %r12,%rcx
	mov    %rax,%r8
	mov    %r15,%r9
	call   <inf_store::store::CellStore::get_str+OFF>
	cmpl   $0x1,0x8(%rsp)
	jne    <inf_store::store::CellStore::get_str+OFF>
	mov    0x10(%rsp),%rax
	mov    0x18(%rsp),%rdx
	incq   0x22c8(%r14)
	mov    0x40(%r14),%rsi
	mov    %rax,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::get_str+OFF>
	mov    0x38(%r14),%rcx
	shl    $0x4,%rdi
	and    $0x1fffff,%eax
	lea    (%rax,%rdx,1),%rsi
	cmp    0x8(%rcx,%rdi,1),%rsi
	ja     <inf_store::store::CellStore::get_str+OFF>
	test   %rdx,%rdx
	je     <inf_store::store::CellStore::get_str+OFF>
	add    %rdi,%rcx
	add    (%rcx),%rax
	movzbl (%rax),%ecx
	mov    %ecx,%esi
	shr    $0x4,%esi
	cmp    $0x1,%esi
	je     <inf_store::store::CellStore::get_str+OFF>
	cmp    $0x2,%esi
	jne    <inf_store::store::CellStore::get_str+OFF>
	movb   $0x6,0x1(%rbx)
	mov    $0x1,%al
	jmp    <inf_store::store::CellStore::get_str+OFF>
	incq   0x22d0(%r14)
	movq   $0x0,0x8(%rbx)
	jmp    <inf_store::store::CellStore::get_str+OFF>
	cmp    $0x1,%rdx
	je     <inf_store::store::CellStore::get_str+OFF>
	cmp    $0x4,%rdx
	jbe    <inf_store::store::CellStore::get_str+OFF>
	movzbl %cl,%ecx
	and    $0x1,%ecx
	lea    (%rcx,%rcx,4),%rcx
	movzbl 0x1(%rax),%esi
	lea    (%rsi,%rcx,1),%rdi
	add    $0x8,%rdi
	movzwl 0x2(%rax),%esi
	movzbl 0x4(%rax),%ecx
	shl    $0x10,%ecx
	or     %rsi,%rcx
	lea    (%rdi,%rcx,1),%rsi
	cmp    %rdx,%rsi
	ja     <inf_store::store::CellStore::get_str+OFF>
	add    %rdi,%rax
	mov    %rax,0x8(%rbx)
	mov    %rcx,0x10(%rbx)
	xor    %eax,%eax
	mov    %al,(%rbx)
	mov    %rbx,%rax
	add    $0x20,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_str+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_str+OFF>
	mov    $0x10,%esi
	call   <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_str+OFF>
	mov    $0x2,%edi
	mov    $0x5,%esi
	call   <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_str+OFF>
	call   <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_str+OFF>
	call   <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_str+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <inf_store::store::CellStore::get_str+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_str+OFF>
	mov    $0x1,%edi
	mov    $0x1,%esi
	call   <.Llocal+OFF>



<inf_store::store::CellStore::get_with_hash>:
	push   %rbx
	sub    $0x20,%rsp
	mov    %r8,%r9
	mov    %rcx,%r8
	mov    %rdx,%rcx
	mov    %rsi,%rdx
	mov    %rdi,%rbx
	lea    0x8(%rsp),%rdi
	mov    %rbx,%rsi
	call   <inf_store::store::CellStore::get_with_hash+OFF>
	cmpl   $0x1,0x8(%rsp)
	jne    <inf_store::store::CellStore::get_with_hash+OFF>
	mov    0x10(%rsp),%rax
	mov    0x18(%rsp),%rdx
	incq   0x22c8(%rbx)
	mov    0x40(%rbx),%rsi
	mov    %rax,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::get_with_hash+OFF>
	mov    0x38(%rbx),%rcx
	shl    $0x4,%rdi
	and    $0x1fffff,%eax
	lea    (%rax,%rdx,1),%rsi
	cmp    0x8(%rcx,%rdi,1),%rsi
	ja     <inf_store::store::CellStore::get_with_hash+OFF>
	cmp    $0x1,%rdx
	je     <inf_store::store::CellStore::get_with_hash+OFF>
	test   %rdx,%rdx
	je     <inf_store::store::CellStore::get_with_hash+OFF>
	cmp    $0x4,%rdx
	jbe    <inf_store::store::CellStore::get_with_hash+OFF>
	add    %rdi,%rcx
	add    (%rcx),%rax
	movzbl (%rax),%ecx
	and    $0x1,%ecx
	lea    (%rcx,%rcx,4),%rcx
	movzbl 0x1(%rax),%esi
	lea    (%rsi,%rcx,1),%rdi
	add    $0x8,%rdi
	movzwl 0x2(%rax),%esi
	movzbl 0x4(%rax),%ecx
	shl    $0x10,%ecx
	or     %rsi,%rcx
	lea    (%rdi,%rcx,1),%rsi
	cmp    %rdx,%rsi
	ja     <inf_store::store::CellStore::get_with_hash+OFF>
	add    %rdi,%rax
	mov    %rcx,%rdx
	add    $0x20,%rsp
	pop    %rbx
	ret
	incq   0x22d0(%rbx)
	xor    %eax,%eax
	mov    %rcx,%rdx
	add    $0x20,%rsp
	pop    %rbx
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::get_with_hash+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_with_hash+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::get_with_hash+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_with_hash+OFF>
	mov    $0x2,%edi
	mov    $0x5,%esi
	call   <inf_store::store::CellStore::get_with_hash+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::get_with_hash+OFF>
	call   <inf_store::store::CellStore::get_with_hash+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_with_hash+OFF>
	call   <inf_store::store::CellStore::get_with_hash+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_with_hash+OFF>
	mov    $0x1,%edi
	mov    $0x1,%esi
	call   <inf_store::store::CellStore::get_with_hash+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::get_with_hash+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <.Llocal+OFF>



<inf_store::store::CellStore::resolve>:
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	mov    %r8,%rbx
	mov    %rcx,%r14
	mov    %rdx,%r15
	mov    %rsi,%r12
	mov    %rdi,%r13
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %r15,%rdi
	mov    %rcx,%rsi
	call   <inf_store::store::CellStore::resolve+OFF>
	mov    %r13,%rdi
	mov    %r12,%rsi
	mov    %r15,%rdx
	mov    %r14,%rcx
	mov    %rax,%r8
	mov    %rbx,%r9
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	jmp   <.Llocal+OFF>



<inf_store::store::CellStore::resolve_hashed>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0xe8,%rsp
	mov    %rcx,0x8(%rsp)
	mov    %rdx,0x78(%rsp)
	mov    %rdi,(%rsp)
	mov    0x2298(%rsi),%rcx
	mov    0x22b0(%rsi),%rdi
	shr    $0x4,%rdi
	dec    %rdi
	mov    %rdi,%rbx
	and    %r8,%rbx
	mov    %rbx,%rax
	shl    $0x4,%rax
	mov    %rax,%r14
	add    $0xf,%rax
	mov    %rcx,0x18(%rsp)
	cmp    %rcx,%rax
	jae    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %r9,0x30(%rsp)
	lea    0x2290(%rsi),%rax
	mov    %rax,0x28(%rsp)
	mov    %r8,%rcx
	shr    $0x2a,%rcx
	mov    %r8,0x10(%rsp)
	mov    %r8,%rax
	shr    $0x39,%rax
	mov    0x2290(%rsi),%rdx
	mov    %rdx,0x48(%rsp)
	movd   %eax,%xmm0
	punpcklbw %xmm0,%xmm0
	pshuflw $0x0,%xmm0,%xmm0
	pshufd $0x44,%xmm0,%xmm0
	movdqa %xmm0,0xa0(%rsp)
	mov    0x22a8(%rsi),%rax
	mov    %rax,0x20(%rsp)
	mov    0x22a0(%rsi),%rax
	mov    %rax,0x98(%rsp)
	mov    0x38(%rsi),%r11
	mov    %rsi,0x38(%rsp)
	mov    0x40(%rsi),%r10
	mov    %rcx,%rsi
	xor    %r8d,%r8d
	mov    0x8(%rsp),%rdx
	mov    %r14,%rcx
	mov    %r11,0x70(%rsp)
	mov    %rdi,0x40(%rsp)
	mov    %rsi,0x68(%rsp)
	mov    %r10,0x60(%rsp)
	nopl   0x0(%rax,%rax,1)
	mov    %r8,0x58(%rsp)
	mov    %rbx,0x50(%rsp)
	mov    0x48(%rsp),%rax
	movdqu (%rax,%rcx,1),%xmm1
	movdqa 0xa0(%rsp),%xmm0
	movdqa %xmm1,0xb0(%rsp)
	pcmpeqb %xmm1,%xmm0
	pmovmskb %xmm0,%eax
	test   %eax,%eax
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	movdqa 0xb0(%rsp),%xmm0
	pcmpeqb 0x0(%rip),%xmm0        # <inf_store::store::CellStore::resolve_hashed+OFF>
	pmovmskb %xmm0,%eax
	test   %eax,%eax
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x58(%rsp),%r8
	inc    %r8
	mov    0x40(%rsp),%rdi
	cmp    %rdi,%r8
	ja     <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x50(%rsp),%rbx
	add    %r8,%rbx
	and    %rdi,%rbx
	mov    %rbx,%rcx
	shl    $0x4,%rcx
	lea    0xf(%rcx),%rax
	cmp    0x18(%rsp),%rax
	jb     <inf_store::store::CellStore::resolve_hashed+OFF>
	jmp    <inf_store::store::CellStore::resolve_hashed+OFF>
	nopl   0x0(%rax,%rax,1)
	lea    -0x1(%r14),%eax
	and    %r14d,%eax
	test   %ax,%ax
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %eax,%r14d
	tzcnt  %r14d,%edi
	or     %rcx,%rdi
	cmp    0x20(%rsp),%rdi
	jae    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x98(%rsp),%rax
	mov    (%rax,%rdi,8),%r12
	mov    %r12,%rax
	shr    $0x30,%rax
	xor    %esi,%eax
	test   $0x7fff,%eax
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %r12,%r9
	movabs $0xffffffffffff,%rax
	and    %rax,%r9
	mov    %r9,%rdi
	shr    $0x15,%rdi
	cmp    %r10,%rdi
	jae    <inf_store::store::CellStore::resolve_hashed+OFF>
	shl    $0x4,%edi
	and    $0x1fffff,%r12d
	lea    0x8(%r12),%rax
	mov    0x8(%r11,%rdi,1),%r15
	cmp    %r15,%rax
	ja     <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %rcx,%r13
	add    %r11,%rdi
	mov    (%rdi),%rbx
	movzbl (%rbx,%r12,1),%edi
	movzbl 0x1(%rbx,%r12,1),%eax
	movzwl 0x2(%rbx,%r12,1),%ecx
	movzbl 0x4(%rbx,%r12,1),%ebp
	shl    $0x10,%ebp
	or     %rcx,%rbp
	mov    %edi,%ecx
	and    $0x1,%ecx
	lea    (%rcx,%rcx,4),%r8
	add    $0x8,%r8
	lea    (%r12,%rax,1),%rcx
	add    %r8,%rcx
	add    %rbp,%rcx
	cmp    %r15,%rcx
	ja     <inf_store::store::CellStore::resolve_hashed+OFF>
	cmp    %rax,%rdx
	mov    %r13,%rcx
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	add    %r12,%rbx
	mov    %rdi,0x80(%rsp)
	lea    (%rbx,%r8,1),%rdi
	mov    0x78(%rsp),%rsi
	mov    0x8(%rsp),%rdx
	mov    %r9,0x90(%rsp)
	mov    %r8,0x88(%rsp)
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x80(%rsp),%rdi
	mov    %r13,%rcx
	mov    0x68(%rsp),%rsi
	mov    0x8(%rsp),%rdx
	mov    0x70(%rsp),%r11
	mov    0x60(%rsp),%r10
	mov    0x88(%rsp),%r8
	mov    0x90(%rsp),%r13
	test   %eax,%eax
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	add    %rdx,%r8
	add    %rbp,%r8
	add    %r8,%r12
	cmp    %r15,%r12
	ja     <inf_store::store::CellStore::resolve_hashed+OFF>
	test   $0x1,%dil
	mov    0x38(%rsp),%r15
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	cmp    $0xc,%r8
	jbe    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x8(%rbx),%ecx
	movabs $0x431bde82d7b634db,%rdx
	mov    0x30(%rsp),%rax
	mul    %rdx
	movzbl 0xc(%rbx),%eax
	shl    $0x20,%rax
	or     %rcx,%rax
	shr    $0x12,%rdx
	cmp    %rax,%rdx
	jae    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %r8,%r12
	movzbl 0x2289(%r15),%eax
	test   %eax,%eax
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	cmp    $0x1,%eax
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	or     $0xc,%dil
	mov    %dil,(%rbx)
	jmp    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    (%rsp),%rax
	xor    %ecx,%ecx
	jmp    <inf_store::store::CellStore::resolve_hashed+OFF>
	movabs $0x9e3779b97f4a7c15,%rax
	add    0x2278(%r15),%rax
	mov    %rax,0x2278(%r15)
	mov    0x2270(%r15),%rcx
	test   %rcx,%rcx
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x10(%rsp),%rdx
	mov    %edx,%r8d
	shr    $0xb,%r8d
	and    $0x7ff,%r8d
	mov    %rdx,%rdi
	shr    $0x16,%rdi
	and    $0x7ff,%edi
	mov    %rdx,%rsi
	shr    $0x21,%rsi
	and    $0x7ff,%esi
	and    $0x7ff,%edx
	movzbl (%rcx,%rdx,1),%r14d
	movzbl 0x800(%rcx,%r8,1),%ebx
	movzbl 0x1000(%rcx,%rdi,1),%r9d
	cmp    %bl,%r14b
	mov    %ebx,%ebp
	cmovb  %r14d,%ebp
	cmp    %r9b,%bpl
	cmovae %r9d,%ebp
	mov    %ebp,%r11d
	movzbl 0x1800(%rcx,%rsi,1),%r10d
	cmp    %r10b,%bpl
	cmovae %r10d,%ebp
	cmp    $0xff,%bpl
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %rdx,%r15
	mov    %rax,%rdx
	shr    $0x1e,%rdx
	xor    %rax,%rdx
	movabs $0xbf58476d1ce4e5b9,%rax
	imul   %rdx,%rax
	mov    %rax,%rdx
	shr    $0x1b,%rdx
	xor    %rax,%rdx
	movabs $0x94d049bb133111eb,%rax
	imul   %rdx,%rax
	mov    %rax,%rdx
	shr    $0x1f,%rdx
	xor    %rax,%rdx
	movzbl %bpl,%eax
	add    %eax,%eax
	lea    (%rax,%rax,4),%rax
	inc    %rax
	mul    %rdx
	jo     <inf_store::store::CellStore::resolve_hashed+OFF>
	cmp    %bpl,%r14b
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	cmp    %bpl,%bl
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	cmp    %bpl,%r9b
	je     <inf_store::store::CellStore::resolve_hashed+OFF>
	cmp    %r11b,%r10b
	ja     <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x1(%r10),%eax
	mov    %al,0x1800(%rcx,%rsi,1)
	mov    (%rsp),%rax
	mov    %r13,0x8(%rax)
	mov    %r12,0x10(%rax)
	mov    $0x1,%ecx
	jmp    <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0xc8(%rsp),%r14
	mov    %r14,%rdi
	mov    %r11,%rsi
	mov    %r10,%rdx
	mov    %r13,%rcx
	mov    %r8,%rbx
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x28(%rsp),%rdi
	mov    0x10(%rsp),%rsi
	mov    %r13,%rdx
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %r15,%rdi
	mov    %r13,%rsi
	mov    %rbx,%rdx
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x80(%r15),%rdi
	mov    %r14,%rsi
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	incq   0x22d8(%r15)
	mov    0x22e8(%r15),%rax
	cmp    $0x1,%rax
	adc    $0xffffffffffffffff,%rax
	mov    %rax,0x22e8(%r15)
	xor    %ecx,%ecx
	mov    (%rsp),%rax
	mov    %rcx,(%rax)
	add    $0xe8,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x1(%r14),%eax
	mov    %al,(%rcx,%r15,1)
	cmp    %bpl,%bl
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x1(%rbx),%eax
	mov    %al,0x800(%rcx,%r8,1)
	cmp    %bpl,%r9b
	jne    <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x1(%r9),%eax
	mov    %al,0x1000(%rcx,%rdi,1)
	cmp    %r11b,%r10b
	jbe    <inf_store::store::CellStore::resolve_hashed+OFF>
	jmp    <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %r14,%rcx
	lea    0x10(%rcx),%rsi
	mov    %rcx,%rdi
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x18(%rsp),%rdx
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    $0x8,%edi
	mov    $0xd,%esi
	mov    %r8,%rdx
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    0x20(%rsp),%rsi
	call   <inf_store::store::CellStore::resolve_hashed+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::resolve_hashed+OFF>
	mov    %r10,%rsi
	call   <.Lswitch.table._ZN9inf_store7catalog9NsCatalog6encode17hb15ce09b8ccb2dc1E+OFF>



<inf_store::store::CellStore::set>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0xf8,%rsp
	mov    %rcx,%r15
	mov    %rdi,%rbx
	cmp    $0x100,%rcx
	setae  %al
	cmp    $0x1000000,%r9
	setae  %cl
	or     %al,%cl
	je     <inf_store::store::CellStore::set+OFF>
	movb   $0x5,0x8(%rbx)
	movq   $0x2,(%rbx)
	jmp    <inf_store::store::CellStore::set+OFF>
	mov    %r9,%rbp
	mov    %rdx,%r12
	mov    %rsi,%r14
	mov    %r8,0x50(%rsp)
	mov    0x138(%rsp),%r13
	movabs $0x8000000000000000,%rax
	mov    %rax,0x8(%rsp)
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %r12,%rdi
	mov    %r15,%rsi
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x30(%rsp),%rdi
	mov    %r14,%rsi
	mov    %r12,%rdx
	mov    %r15,%rcx
	mov    %rax,%r8
	mov    %r13,%r9
	call   <inf_store::store::CellStore::set+OFF>
	mov    0x30(%rsp),%r8
	cmp    $0x1,%r8
	jne    <inf_store::store::CellStore::set+OFF>
	mov    0x38(%rsp),%r13
	mov    0x40(%r14),%rsi
	mov    %r13,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::set+OFF>
	mov    0x40(%rsp),%rdx
	mov    0x38(%r14),%rax
	shl    $0x4,%rdi
	and    $0x1fffff,%r13d
	lea    (%rdx,%r13,1),%rcx
	cmp    0x8(%rax,%rdi,1),%rcx
	ja     <inf_store::store::CellStore::set+OFF>
	add    %rdi,%rax
	mov    (%rax),%rax
	add    %rax,%r13
	mov    0x130(%rsp),%r9
	cmpb   $0x0,0x10(%r9)
	je     <inf_store::store::CellStore::set+OFF>
	test   %rax,%rax
	je     <inf_store::store::CellStore::set+OFF>
	test   %rdx,%rdx
	je     <inf_store::store::CellStore::set+OFF>
	movzbl 0x0(%r13),%eax
	mov    %eax,%ecx
	shr    $0x4,%cl
	lea    -0x1(%rcx),%esi
	cmp    $0x2,%sil
	jae    <inf_store::store::CellStore::set+OFF>
	cmp    $0x1,%cl
	jne    <inf_store::store::CellStore::set+OFF>
	test   $0x1,%al
	jne    <inf_store::store::CellStore::set+OFF>
	cmp    $0x1,%rdx
	je     <inf_store::store::CellStore::set+OFF>
	cmp    $0x4,%rdx
	jbe    <inf_store::store::CellStore::set+OFF>
	movzbl 0x1(%r13),%edi
	add    $0x8,%rdi
	movq   $0x0,0x10(%rsp)
	jmp    <inf_store::store::CellStore::set+OFF>
	xor    %r13d,%r13d
	movq   $0x0,0x10(%rsp)
	mov    0x130(%rsp),%r9
	jmp    <inf_store::store::CellStore::set+OFF>
	test   %rax,%rax
	je     <inf_store::store::CellStore::set+OFF>
	test   %rdx,%rdx
	je     <inf_store::store::CellStore::set+OFF>
	testb  $0x1,0x0(%r13)
	jne    <inf_store::store::CellStore::set+OFF>
	movq   $0x0,0x10(%rsp)
	jmp    <inf_store::store::CellStore::set+OFF>
	xor    %r13d,%r13d
	movq   $0x0,0x10(%rsp)
	jmp    <inf_store::store::CellStore::set+OFF>
	cmp    $0xc,%rdx
	jbe    <inf_store::store::CellStore::set+OFF>
	mov    0x8(%r13),%eax
	movzbl 0xc(%r13),%ecx
	shl    $0x20,%rcx
	or     %rax,%rcx
	mov    %rcx,0x28(%rsp)
	mov    $0x1,%eax
	mov    %rax,0x10(%rsp)
	jmp    <inf_store::store::CellStore::set+OFF>
	movb   $0x6,0x8(%rbx)
	jmp    <inf_store::store::CellStore::set+OFF>
	cmp    $0xc,%rdx
	jbe    <inf_store::store::CellStore::set+OFF>
	mov    0x8(%r13),%eax
	movzbl 0xc(%r13),%ecx
	shl    $0x20,%rcx
	or     %rax,%rcx
	mov    %rcx,0x28(%rsp)
	movzbl 0x1(%r13),%edi
	add    $0xd,%rdi
	mov    $0x1,%eax
	mov    %rax,0x10(%rsp)
	mov    %r8,0x20(%rsp)
	movzwl 0x2(%r13),%eax
	movzbl 0x4(%r13),%ecx
	shl    $0x10,%ecx
	or     %rax,%rcx
	lea    (%rdi,%rcx,1),%rsi
	cmp    %rdx,%rsi
	ja     <inf_store::store::CellStore::set+OFF>
	test   %rcx,%rcx
	je     <inf_store::store::CellStore::set+OFF>
	mov    %rdi,0x18(%rsp)
	mov    %rdx,0x48(%rsp)
	mov    %rcx,0x8(%rsp)
	call   <inf_store::store::CellStore::set+OFF>
	mov    $0x1,%esi
	mov    0x8(%rsp),%rdi
	call   <inf_store::store::CellStore::set+OFF>
	test   %rax,%rax
	je     <inf_store::store::CellStore::set+OFF>
	mov    0x18(%rsp),%rsi
	add    %r13,%rsi
	mov    %rax,0x18(%rsp)
	mov    %rax,%rdi
	mov    0x8(%rsp),%rdx
	call   <inf_store::store::CellStore::set+OFF>
	mov    0x20(%rsp),%r8
	mov    0x130(%rsp),%r9
	mov    0x48(%rsp),%rdx
	jmp    <inf_store::store::CellStore::set+OFF>
	mov    $0x1,%eax
	mov    %rax,0x18(%rsp)
	movq   $0x0,0x8(%rsp)
	mov    0x20(%rsp),%r8
	movzbl 0x11(%r9),%eax
	test   %eax,%eax
	je     <inf_store::store::CellStore::set+OFF>
	cmp    $0x1,%eax
	jne    <inf_store::store::CellStore::set+OFF>
	test   %r8b,%r8b
	je     <inf_store::store::CellStore::set+OFF>
	movq   $0x1,(%rbx)
	jmp    <inf_store::store::CellStore::set+OFF>
	test   %r8b,%r8b
	je     <inf_store::store::CellStore::set+OFF>
	test   %r13,%r13
	mov    %r12,0x20(%rsp)
	je     <inf_store::store::CellStore::set+OFF>
	cmp    $0x7,%rdx
	jbe    <inf_store::store::CellStore::set+OFF>
	movzbl 0x7(%r13),%eax
	shl    $0x10,%eax
	movzwl 0x5(%r13),%ecx
	add    %eax,%ecx
	inc    %ecx
	mov    (%r9),%r12
	test   %r12,%r12
	je     <inf_store::store::CellStore::set+OFF>
	mov    0x28(%rsp),%r13
	cmp    $0x2,%r12d
	mov    0x10(%rsp),%r12
	jne    <inf_store::store::CellStore::set+OFF>
	movabs $0x431bde82d7b634db,%rax
	mulq   0x8(%r9)
	mov    %rdx,%r13
	shr    $0x12,%r13
	movabs $0xffffffffff,%rax
	cmp    %rax,%r13
	cmovae %rax,%r13
	mov    $0x1,%r12d
	jmp    <inf_store::store::CellStore::set+OFF>
	mov    $0x1,%ecx
	mov    (%r9),%r12
	test   %r12,%r12
	jne    <inf_store::store::CellStore::set+OFF>
	mov    0x20(%rsp),%rsi
	mov    %rsi,0x68(%rsp)
	mov    %r15,0x70(%rsp)
	mov    0x50(%rsp),%rax
	mov    %rax,0x78(%rsp)
	mov    %rbp,0x80(%rsp)
	mov    %ecx,0x88(%rsp)
	mov    %r12,0x58(%rsp)
	mov    %r13,0x60(%rsp)
	movb   $0x0,0x8c(%rsp)
	test   %r8b,%r8b
	je     <inf_store::store::CellStore::set+OFF>
	mov    0x38(%rsp),%rcx
	mov    0x40(%rsp),%r8
	mov    0x38(%r14),%rsi
	mov    0x40(%r14),%rdx
	lea    0xd8(%rsp),%rdi
	call   <inf_store::store::CellStore::set+OFF>
	mov    0xd8(%rsp),%ebp
	movups 0xdc(%rsp),%xmm0
	movaps %xmm0,0x90(%rsp)
	movups 0xe8(%rsp),%xmm0
	movups %xmm0,0x9c(%rsp)
	lea    0x30(%rsp),%rcx
	lea    0x58(%rsp),%r8
	mov    %r14,%rdi
	mov    0x20(%rsp),%rsi
	mov    %r15,%rdx
	call   <inf_store::store::CellStore::set+OFF>
	cmp    $0x7,%al
	jne    <inf_store::store::CellStore::set+OFF>
	mov    %ebp,0xb8(%rsp)
	movaps 0x90(%rsp),%xmm0
	movups %xmm0,0xbc(%rsp)
	movups 0x9c(%rsp),%xmm0
	movups %xmm0,0xc8(%rsp)
	lea    0x80(%r14),%rdi
	lea    0xb8(%rsp),%rsi
	call   <inf_store::store::CellStore::set+OFF>
	jmp    <inf_store::store::CellStore::set+OFF>
	lea    0x30(%rsp),%rcx
	lea    0x58(%rsp),%r8
	mov    %r14,%rdi
	mov    %r15,%rdx
	call   <inf_store::store::CellStore::set+OFF>
	cmp    $0x7,%al
	jne    <inf_store::store::CellStore::set+OFF>
	cmpq   $0x0,0x10(%rsp)
	je     <inf_store::store::CellStore::set+OFF>
	cmp    $0x1,%r12d
	jne    <inf_store::store::CellStore::set+OFF>
	cmp    %r13,0x28(%rsp)
	jne    <inf_store::store::CellStore::set+OFF>
	jmp    <inf_store::store::CellStore::set+OFF>
	mov    %al,0x8(%rbx)
	movq   $0x2,(%rbx)
	mov    0x8(%rsp),%rsi
	lea    0x0(,%rsi,2),%rax
	test   %rax,%rax
	je     <inf_store::store::CellStore::set+OFF>
	mov    $0x1,%edx
	mov    0x18(%rsp),%rdi
	call   <inf_store::store::CellStore::set+OFF>
	jmp    <inf_store::store::CellStore::set+OFF>
	cmp    $0x1,%r12d
	jne    <inf_store::store::CellStore::set+OFF>
	incq   0x22e8(%r14)
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    0x20(%rsp),%rdi
	mov    %r15,%rsi
	call   <inf_store::store::CellStore::set+OFF>
	mov    %r14,%rdi
	mov    %rax,%rsi
	mov    %r13,%rdx
	call   <inf_store::store::CellStore::set+OFF>
	jmp    <inf_store::store::CellStore::set+OFF>
	mov    0x22e8(%r14),%rax
	cmp    $0x1,%rax
	adc    $0xffffffffffffffff,%rax
	mov    %rax,0x22e8(%r14)
	movq   $0x0,(%rbx)
	mov    0x8(%rsp),%rax
	mov    %rax,0x8(%rbx)
	mov    0x18(%rsp),%rcx
	mov    %rcx,0x10(%rbx)
	mov    %rax,0x18(%rbx)
	mov    %rbx,%rax
	add    $0xf8,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set+OFF>
	mov    $0x5,%edi
	mov    $0x8,%esi
	call   <inf_store::store::CellStore::set+OFF>
	ud2
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set+OFF>
	mov    $0x8,%edi
	mov    $0xd,%esi
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set+OFF>
	mov    $0x10,%esi
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set+OFF>
	mov    $0x2,%edi
	mov    $0x5,%esi
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set+OFF>
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set+OFF>
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <inf_store::store::CellStore::set+OFF>
	mov    $0x1,%edi
	mov    0x8(%rsp),%rsi
	call   <inf_store::store::CellStore::set+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set+OFF>
	mov    $0x1,%edi
	mov    $0x1,%esi
	call   <inf_store::store::CellStore::set+OFF>
	mov    0x8(%rsp),%rsi
	lea    0x0(,%rsi,2),%rcx
	test   %rcx,%rcx
	je     <inf_store::store::CellStore::set+OFF>
	mov    $0x1,%edx
	mov    0x18(%rsp),%rdi
	mov    %rax,%rbx
	call   <inf_store::store::CellStore::set+OFF>
	mov    %rbx,%rax
	mov    %rax,%rdi
	call   <.Lswitch.table._ZN9inf_store7catalog9NsCatalog6encode17hb15ce09b8ccb2dc1E+OFF>



<inf_store::store::CellStore::set_eviction_policy>:
	push   %rbx
	mov    %rdi,%rbx
	mov    %sil,0x2288(%rdi)
	movzbl %sil,%eax
	lea    -0x6(%rax),%ecx
	cmp    $0x2,%ecx
	jb     <inf_store::store::CellStore::set_eviction_policy+OFF>
	dec    %eax
	cmp    $0x1,%eax
	ja     <inf_store::store::CellStore::set_eviction_policy+OFF>
	mov    $0x1,%al
	mov    %al,0x2289(%rbx)
	mov    0x2270(%rbx),%rdi
	test   %rdi,%rdi
	je     <inf_store::store::CellStore::set_eviction_policy+OFF>
	mov    $0x2000,%esi
	mov    $0x1,%edx
	call   <inf_store::store::CellStore::set_eviction_policy+OFF>
	movq   $0x0,0x2270(%rbx)
	pop    %rbx
	ret
	movb   $0x2,0x2289(%rbx)
	cmpq   $0x0,0x2270(%rbx)
	je     <inf_store::store::CellStore::set_eviction_policy+OFF>
	pop    %rbx
	ret
	xor    %eax,%eax
	mov    %al,0x2289(%rbx)
	mov    0x2270(%rbx),%rdi
	test   %rdi,%rdi
	jne    <inf_store::store::CellStore::set_eviction_policy+OFF>
	jmp    <inf_store::store::CellStore::set_eviction_policy+OFF>
	call   <inf_store::store::CellStore::set_eviction_policy+OFF>
	mov    $0x2000,%edi
	mov    $0x1,%esi
	call   <inf_store::store::CellStore::set_eviction_policy+OFF>
	test   %rax,%rax
	je     <inf_store::store::CellStore::set_eviction_policy+OFF>
	mov    %rax,0x2270(%rbx)
	pop    %rbx
	ret
	mov    $0x1,%edi
	mov    $0x2000,%esi
	call   <.Llocal+OFF>



<inf_store::store::CellStore::set_range>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0x118,%rsp
	mov    %r9,0x70(%rsp)
	mov    %r8,%rbp
	mov    %rcx,%r13
	mov    %rdx,%r14
	mov    %rsi,%r15
	mov    %rdi,0x8(%rsp)
	mov    0x150(%rsp),%r12
	mov    0x158(%rsp),%rbx
	movabs $0x1af1d8a50db5eed1,%rdx
	mov    %r14,%rdi
	mov    %rcx,%rsi
	call   <inf_store::store::CellStore::set_range+OFF>
	lea    0x30(%rsp),%rdi
	mov    %r15,0x20(%rsp)
	mov    %r15,%rsi
	mov    %r14,%r15
	mov    %r14,%rdx
	mov    %r13,%rcx
	mov    %rax,%r8
	mov    %rbx,%r9
	call   <inf_store::store::CellStore::set_range+OFF>
	test   %r12,%r12
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    %rbp,%rax
	mov    %r12,%rbp
	mov    %rax,0x68(%rsp)
	add    %rax,%rbp
	jb     <inf_store::store::CellStore::set_range+OFF>
	cmp    $0x100,%r13
	setae  %al
	cmp    $0x1000000,%rbp
	setae  %cl
	or     %al,%cl
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    0x8(%rsp),%rbx
	movw   $0x501,(%rbx)
	jmp    <inf_store::store::CellStore::set_range+OFF>
	cmpb   $0x0,0x30(%rsp)
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    0x38(%rsp),%rax
	mov    0x20(%rsp),%r13
	mov    0x40(%r13),%rsi
	mov    %rax,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::set_range+OFF>
	mov    0x40(%rsp),%rdx
	mov    0x38(%r13),%rcx
	shl    $0x4,%rdi
	and    $0x1fffff,%eax
	lea    (%rax,%rdx,1),%rsi
	cmp    0x8(%rcx,%rdi,1),%rsi
	ja     <inf_store::store::CellStore::set_range+OFF>
	cmp    $0x4,%rdx
	mov    0x8(%rsp),%rbx
	jbe    <inf_store::store::CellStore::set_range+OFF>
	add    %rdi,%rcx
	mov    (%rcx),%rcx
	movzwl 0x2(%rcx,%rax,1),%edx
	movzbl 0x4(%rcx,%rax,1),%eax
	shl    $0x10,%eax
	or     %rdx,%rax
	jmp    <inf_store::store::CellStore::set_range+OFF>
	mov    %r13,0x60(%rsp)
	movzbl 0x30(%rsp),%r13d
	test   %r13b,%r13b
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    0x38(%rsp),%rbx
	mov    0x20(%rsp),%r14
	mov    0x40(%r14),%rsi
	mov    %rbx,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::set_range+OFF>
	mov    0x40(%rsp),%rdx
	mov    0x38(%r14),%rax
	shl    $0x4,%rdi
	and    $0x1fffff,%ebx
	lea    (%rbx,%rdx,1),%rcx
	cmp    0x8(%rax,%rdi,1),%rcx
	ja     <inf_store::store::CellStore::set_range+OFF>
	test   %rdx,%rdx
	je     <inf_store::store::CellStore::set_range+OFF>
	add    %rdi,%rax
	add    (%rax),%rbx
	movzbl (%rbx),%eax
	mov    %eax,%ecx
	shr    $0x4,%ecx
	cmp    $0x1,%ecx
	je     <inf_store::store::CellStore::set_range+OFF>
	cmp    $0x2,%ecx
	jne    <inf_store::store::CellStore::set_range+OFF>
	mov    0x8(%rsp),%rbx
	movw   $0x601,(%rbx)
	jmp    <inf_store::store::CellStore::set_range+OFF>
	xor    %eax,%eax
	mov    0x8(%rsp),%rbx
	mov    %rax,0x8(%rbx)
	movb   $0x0,(%rbx)
	jmp    <inf_store::store::CellStore::set_range+OFF>
	mov    %r13b,0x7(%rsp)
	mov    $0x1,%ecx
	mov    $0x1,%r13d
	movq   $0x0,0x18(%rsp)
	xor    %r12d,%r12d
	mov    0x20(%rsp),%r14
	jmp    <inf_store::store::CellStore::set_range+OFF>
	cmp    $0x1,%rdx
	je     <inf_store::store::CellStore::set_range+OFF>
	cmp    $0x4,%rdx
	jbe    <inf_store::store::CellStore::set_range+OFF>
	movzbl %al,%ecx
	and    $0x1,%ecx
	lea    (%rcx,%rcx,4),%rcx
	movzbl 0x1(%rbx),%esi
	lea    (%rsi,%rcx,1),%rdi
	add    $0x8,%rdi
	movzwl 0x2(%rbx),%ecx
	movzbl 0x4(%rbx),%r12d
	shl    $0x10,%r12d
	or     %rcx,%r12
	lea    (%rdi,%r12,1),%rsi
	cmp    %rdx,%rsi
	ja     <inf_store::store::CellStore::set_range+OFF>
	test   %r12,%r12
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    %rdi,0x10(%rsp)
	mov    %rdx,0x18(%rsp)
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    $0x1,%esi
	mov    %r12,%rdi
	call   <inf_store::store::CellStore::set_range+OFF>
	test   %rax,%rax
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    0x10(%rsp),%rsi
	add    %rbx,%rsi
	mov    %rax,0x28(%rsp)
	mov    %rax,%rdi
	mov    %r12,%rdx
	call   <inf_store::store::CellStore::set_range+OFF>
	movzbl (%rbx),%eax
	and    $0x1,%al
	mov    0x18(%rsp),%rdx
	jmp    <inf_store::store::CellStore::set_range+OFF>
	and    $0x1,%al
	mov    $0x1,%ecx
	mov    %rcx,0x28(%rsp)
	movzwl 0x5(%rbx),%esi
	movzbl 0x7(%rbx),%ecx
	test   %al,%al
	mov    %r13b,0x7(%rsp)
	je     <inf_store::store::CellStore::set_range+OFF>
	cmp    $0xc,%rdx
	jbe    <inf_store::store::CellStore::set_range+OFF>
	mov    0x8(%rbx),%eax
	movzbl 0xc(%rbx),%edx
	shl    $0x20,%rdx
	or     %rax,%rdx
	mov    %rdx,0x10(%rsp)
	mov    $0x1,%eax
	mov    %rax,0x18(%rsp)
	jmp    <inf_store::store::CellStore::set_range+OFF>
	movq   $0x0,0x18(%rsp)
	shl    $0x10,%ecx
	mov    %esi,%r13d
	or     %ecx,%r13d
	inc    %r13d
	mov    0x28(%rsp),%rcx
	mov    %r12,0x48(%rsp)
	mov    %rcx,0x50(%rsp)
	mov    %r12,0x58(%rsp)
	mov    %rbp,%rbx
	sub    %r12,%rbx
	jbe    <inf_store::store::CellStore::set_range+OFF>
	lea    0x48(%rsp),%rdi
	mov    $0x1,%ecx
	mov    $0x1,%r8d
	mov    %r12,%rsi
	mov    %rbx,%rdx
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    0x50(%rsp),%r14
	mov    0x58(%rsp),%r12
	lea    (%r14,%r12,1),%rdi
	cmp    $0x2,%rbx
	jb     <inf_store::store::CellStore::set_range+OFF>
	lea    -0x1(%rbx),%rdx
	xor    %esi,%esi
	call   <inf_store::store::CellStore::set_range+OFF>
	add    %rbx,%r12
	dec    %r12
	mov    %r14,%rax
	lea    (%r14,%r12,1),%rdi
	jmp    <inf_store::store::CellStore::set_range+OFF>
	mov    %rcx,%rax
	mov    0x10(%rsp),%rbx
	jmp    <inf_store::store::CellStore::set_range+OFF>
	mov    %r14,%rax
	mov    0x10(%rsp),%rbx
	movb   $0x0,(%rdi)
	inc    %r12
	mov    0x20(%rsp),%r14
	cmp    %r12,%rbp
	ja     <inf_store::store::CellStore::set_range+OFF>
	mov    0x68(%rsp),%rdi
	mov    %rax,%rbp
	add    %rax,%rdi
	mov    0x70(%rsp),%rsi
	mov    0x150(%rsp),%rdx
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    %r15,0x88(%rsp)
	mov    0x60(%rsp),%rdx
	mov    %rdx,0x90(%rsp)
	mov    %rbp,0x98(%rsp)
	mov    %r12,0xa0(%rsp)
	mov    %r13d,0xa8(%rsp)
	mov    0x18(%rsp),%rax
	mov    %rax,0x78(%rsp)
	mov    %rbx,0x80(%rsp)
	movb   $0x1,0xac(%rsp)
	cmpb   $0x0,0x7(%rsp)
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    0x38(%rsp),%rcx
	mov    0x40(%rsp),%r8
	mov    0x38(%r14),%rsi
	mov    0x40(%r14),%rdx
	lea    0xf8(%rsp),%rdi
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    0xf8(%rsp),%ebx
	movups 0xfc(%rsp),%xmm0
	movaps %xmm0,0xb0(%rsp)
	movups 0x108(%rsp),%xmm0
	movups %xmm0,0xbc(%rsp)
	lea    0x30(%rsp),%rcx
	lea    0x78(%rsp),%r8
	mov    %r14,%rdi
	mov    %r15,%rsi
	mov    0x60(%rsp),%rdx
	call   <inf_store::store::CellStore::set_range+OFF>
	cmp    $0x7,%al
	jne    <inf_store::store::CellStore::set_range+OFF>
	mov    %ebx,0xd8(%rsp)
	movaps 0xb0(%rsp),%xmm0
	movups %xmm0,0xdc(%rsp)
	movups 0xbc(%rsp),%xmm0
	movups %xmm0,0xe8(%rsp)
	sub    $0xffffffffffffff80,%r14
	lea    0xd8(%rsp),%rsi
	mov    %r14,%rdi
	call   <inf_store::store::CellStore::set_range+OFF>
	jmp    <inf_store::store::CellStore::set_range+OFF>
	lea    0x30(%rsp),%rcx
	lea    0x78(%rsp),%r8
	mov    %r14,%rdi
	mov    %r15,%rsi
	call   <inf_store::store::CellStore::set_range+OFF>
	cmp    $0x7,%al
	jne    <inf_store::store::CellStore::set_range+OFF>
	mov    0x8(%rsp),%rbx
	mov    %r12,0x8(%rbx)
	movb   $0x0,(%rbx)
	mov    0x48(%rsp),%rsi
	test   %rsi,%rsi
	jne    <inf_store::store::CellStore::set_range+OFF>
	jmp    <inf_store::store::CellStore::set_range+OFF>
	mov    0x8(%rsp),%rbx
	mov    %al,0x1(%rbx)
	movb   $0x1,(%rbx)
	mov    0x48(%rsp),%rsi
	test   %rsi,%rsi
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    $0x1,%edx
	mov    %rbp,%rdi
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    %rbx,%rax
	add    $0x118,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set_range+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set_range+OFF>
	mov    $0x2,%edi
	mov    $0x5,%esi
	call   <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set_range+OFF>
	mov    0x68(%rsp),%rdi
	mov    %rbp,%rsi
	mov    %r12,%rdx
	call   <inf_store::store::CellStore::set_range+OFF>
	jmp    <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set_range+OFF>
	mov    $0x10,%esi
	call   <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set_range+OFF>
	call   <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rcx        # <inf_store::store::CellStore::set_range+OFF>
	mov    $0x8,%edi
	mov    $0xd,%esi
	call   <inf_store::store::CellStore::set_range+OFF>
	ud2
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set_range+OFF>
	call   <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set_range+OFF>
	xor    %edi,%edi
	xor    %esi,%esi
	call   <inf_store::store::CellStore::set_range+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::set_range+OFF>
	mov    $0x1,%edi
	mov    $0x1,%esi
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    $0x1,%edi
	mov    %r12,%rsi
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    %rax,%rbx
	test   %r12d,%r12d
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    $0x1,%edx
	mov    0x28(%rsp),%rdi
	mov    %r12,%rsi
	jmp    <inf_store::store::CellStore::set_range+OFF>
	mov    %rax,%rbx
	mov    0x48(%rsp),%rsi
	test   %rsi,%rsi
	je     <inf_store::store::CellStore::set_range+OFF>
	mov    0x50(%rsp),%rdi
	mov    $0x1,%edx
	call   <inf_store::store::CellStore::set_range+OFF>
	mov    %rbx,%rdi
	call   <.Lswitch.table._ZN9inf_store7catalog9NsCatalog6encode17hb15ce09b8ccb2dc1E+OFF>



<inf_store::store::CellStore::write_record_carrying>:
	push   %rbp
	push   %r15
	push   %r14
	push   %r13
	push   %r12
	push   %rbx
	sub    $0x78,%rsp
	mov    %r8,%r15
	mov    %rcx,%r14
	mov    %rdi,%rbx
	mov    (%r8),%rax
	mov    0x28(%r8),%rcx
	lea    (%rax,%rax,4),%rax
	add    0x18(%r8),%rax
	lea    (%rcx,%rax,1),%r13
	add    $0x8,%r13
	movabs $0x1af1d8a50db5eed1,%rax
	mov    %rsi,%rdi
	mov    %rdx,%rsi
	mov    %rax,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,%r12
	cmpl   $0x1,(%r14)
	jne    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x8(%r14),%rbp
	mov    0x10(%r14),%r14
	mov    %rbx,%rdi
	mov    %rbp,%rsi
	mov    %r14,%rdx
	mov    %r13,%rcx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	test   %al,%al
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x40(%rbx),%rsi
	mov    %rbp,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x38(%rbx),%rax
	shl    $0x4,%rdi
	mov    %ebp,%esi
	and    $0x1fffff,%esi
	lea    (%rsi,%r13,1),%rcx
	cmp    0x8(%rax,%rdi,1),%rcx
	ja     <inf_store::store::CellStore::write_record_carrying+OFF>
	add    %rdi,%rax
	add    (%rax),%rsi
	mov    %r15,%rdi
	mov    %r13,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %r12,0x30(%rsp)
	mov    0x22b0(%rbx),%r12
	mov    0x22b8(%rbx),%rax
	mov    0x22c0(%rbx),%rcx
	lea    (%rcx,%rax,1),%rdx
	imul   $0x64,%rdx,%rdx
	add    $0x64,%rdx
	imul   $0x55,%r12,%rsi
	cmp    %rsi,%rdx
	jbe    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %r13,0x8(%rsp)
	cmp    %rax,%rcx
	setb   %cl
	mov    %r12,%rbp
	shl    %cl,%rbp
	test   %rbp,%rbp
	jns    <inf_store::store::CellStore::write_record_carrying+OFF>
	xor    %r14d,%r14d
	mov    %r14,%rdi
	mov    %rbp,%rsi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rbx,%rdi
	mov    %r13,0x8(%rsp)
	mov    %r13,%rsi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,%rcx
	mov    $0x4,%al
	test   $0x1,%cl
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rdx,%r13
	mov    0x40(%rbx),%rsi
	mov    %rdx,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x38(%rbx),%rax
	shl    $0x4,%rdi
	mov    %r13d,%esi
	and    $0x1fffff,%esi
	mov    0x8(%rsp),%rdx
	lea    (%rsi,%rdx,1),%rcx
	cmp    0x8(%rax,%rdi,1),%rcx
	ja     <inf_store::store::CellStore::write_record_carrying+OFF>
	add    %rdi,%rax
	add    (%rax),%rsi
	mov    %r15,%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x2290(%rbx),%rdi
	mov    %r12,%rsi
	mov    %rbp,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	cmp    $0x1,%rax
	jne    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x22a8(%rbx),%rsi
	cmp    %rsi,%rdx
	jae    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x22a0(%rbx),%rax
	mov    %r12,%rcx
	shl    $0x6,%rcx
	movabs $0x7fff000000000000,%rsi
	and    %rcx,%rsi
	movabs $0x7ffffffffffffff8,%rcx
	add    $0x8,%rcx
	or     %rsi,%rcx
	or     %r13,%rcx
	mov    %rcx,(%rax,%rdx,8)
	mov    %rbx,%rdi
	mov    %rbp,%rsi
	mov    %r14,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %r13,%rbp
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x1,%r14d
	mov    $0x1,%esi
	mov    %rbp,%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,%rdi
	test   %rax,%rax
	jne    <inf_store::store::CellStore::write_record_carrying+OFF>
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x1,%edi
	mov    %rdi,(%rsp)
	mov    $0x80,%esi
	mov    %rbp,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(,%rbp,8),%rsi
	mov    %rbp,%rax
	shr    $0x3d,%rax
	setne  %al
	movabs $0x7ffffffffffffff8,%rcx
	cmp    %rcx,%rsi
	seta   %cl
	or     %al,%cl
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	xor    %r14d,%r14d
	mov    %r14,%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	test   %rsi,%rsi
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rsi,%r13
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x8,%r14d
	mov    $0x8,%esi
	mov    %r13,%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %r13,%rsi
	mov    %rax,%r13
	test   %rax,%rax
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	cmp    $0x2,%rbp
	jb     <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    -0x8(%rsi),%rdx
	mov    %r13,%rdi
	mov    %rsi,%r14
	xor    %esi,%esi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    (%r14,%r13,1),%rax
	add    $0xfffffffffffffff8,%rax
	mov    (%rsp),%rcx
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x8,%r13d
	cmp    $0x2,%rbp
	jae    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %r13,%rax
	test   %rbp,%rbp
	mov    (%rsp),%rcx
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	movq   $0x0,(%rax)
	mov    %rcx,0x40(%rsp)
	mov    %rbp,0x48(%rsp)
	mov    %r13,0x50(%rsp)
	mov    %rbp,0x58(%rsp)
	mov    %rbp,0x60(%rsp)
	xorps  %xmm0,%xmm0
	movups %xmm0,0x68(%rsp)
	mov    0x2298(%rbx),%rax
	mov    %rax,(%rsp)
	test   %r12,%r12
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x2290(%rbx),%rax
	mov    %rax,0x38(%rsp)
	mov    0x22a8(%rbx),%rax
	mov    %rax,0x10(%rsp)
	mov    0x22a0(%rbx),%rax
	mov    %rax,0x28(%rsp)
	mov    0x38(%rbx),%rbp
	mov    0x40(%rbx),%rax
	mov    %rax,0x20(%rsp)
	xor    %r14d,%r14d
	lea    0x0(%rip),%rax        # <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,0x18(%rsp)
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	data16 cs nopw 0x0(%rax,%rax,1)
	inc    %r14
	cmp    %r14,%r12
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	cmp    %r14,(%rsp)
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x38(%rsp),%rax
	cmpb   $0x0,(%rax,%r14,1)
	js     <inf_store::store::CellStore::write_record_carrying+OFF>
	cmp    0x10(%rsp),%r14
	jae    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x28(%rsp),%rax
	mov    (%rax,%r14,8),%rax
	mov    %rax,%r13
	movabs $0xffffffffffff,%rcx
	and    %rcx,%r13
	mov    %r13,%rdi
	shr    $0x15,%rdi
	cmp    0x20(%rsp),%rdi
	jae    <inf_store::store::CellStore::write_record_carrying+OFF>
	shl    $0x4,%edi
	and    $0x1fffff,%eax
	lea    0x8(%rax),%rdx
	mov    0x8(%rbp,%rdi,1),%rcx
	cmp    %rcx,%rdx
	ja     <inf_store::store::CellStore::write_record_carrying+OFF>
	add    %rbp,%rdi
	mov    (%rdi),%rdi
	movzbl 0x1(%rdi,%rax,1),%esi
	movzwl 0x2(%rdi,%rax,1),%edx
	movzbl 0x4(%rdi,%rax,1),%r8d
	shl    $0x10,%r8d
	or     %rdx,%r8
	movzbl (%rdi,%rax,1),%edx
	and    $0x1,%edx
	lea    (%rdx,%rdx,4),%rdx
	add    $0x8,%rdx
	lea    (%rax,%rsi,1),%r9
	add    %rdx,%r9
	add    %r8,%r9
	cmp    %rcx,%r9
	ja     <inf_store::store::CellStore::write_record_carrying+OFF>
	add    %rax,%rdi
	add    %rdx,%rdi
	movabs $0x1af1d8a50db5eed1,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x40(%rsp),%rdi
	mov    %rax,%rsi
	mov    %r13,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    (%rsp),%rsi
	test   %rsi,%rsi
	lea    0x2290(%rbx),%r14
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    (%r14),%rdi
	mov    $0x1,%edx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x22a8(%rbx),%rsi
	test   %rsi,%rsi
	mov    0x8(%rsp),%r13
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x22a0(%rbx),%rdi
	shl    $0x3,%rsi
	mov    $0x8,%edx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x70(%rsp),%rax
	mov    %rax,0x30(%r14)
	movups 0x40(%rsp),%xmm0
	movups 0x50(%rsp),%xmm1
	movups 0x60(%rsp),%xmm2
	movups %xmm2,0x20(%r14)
	movups %xmm1,0x10(%r14)
	movups %xmm0,(%r14)
	mov    %rbx,%rdi
	mov    %r13,%r14
	mov    %r13,%rsi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,%rcx
	mov    $0x4,%al
	test   $0x1,%cl
	mov    0x30(%rsp),%r12
	je     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rdx,%rbp
	mov    0x40(%rbx),%rsi
	mov    %rdx,%rdi
	shr    $0x15,%rdi
	cmp    %rsi,%rdi
	jae    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x38(%rbx),%rax
	shl    $0x4,%rdi
	mov    %ebp,%esi
	and    $0x1fffff,%esi
	lea    (%rsi,%r14,1),%rcx
	cmp    0x8(%rax,%rdi,1),%rcx
	ja     <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %r14,%rdx
	add    %rdi,%rax
	add    (%rax),%rsi
	mov    %r15,%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x2290(%rbx),%rdi
	mov    %r12,%rsi
	mov    %rbp,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rbx,%rdi
	mov    %r12,%rsi
	mov    %rbp,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x7,%al
	add    $0x78,%rsp
	pop    %rbx
	pop    %r12
	pop    %r13
	pop    %r14
	pop    %r15
	pop    %rbp
	ret
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x63,%esi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(%rip),%rdi        # <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x16,%esi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    (%rsp),%rax
	mov    %rax,0x10(%rsp)
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    0x20(%rsp),%rsi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %r14,(%rsp)
	lea    0x0(%rip),%rax        # <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,0x18(%rsp)
	mov    (%rsp),%rdi
	mov    0x10(%rsp),%rsi
	mov    0x18(%rsp),%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	ud2
	lea    0x0(%rip),%rdx        # <inf_store::store::CellStore::write_record_carrying+OFF>
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	lea    0x0(%rip),%rax        # <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rdx,%rdi
	mov    %rax,%rdx
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	jmp    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,%rbx
	lea    0x40(%rsp),%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rbx,%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rax,%rbx
	test   %rbp,%rbp
	jne    <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rbx,%rdi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    $0x1,%edx
	mov    (%rsp),%rdi
	mov    %rbp,%rsi
	call   <inf_store::store::CellStore::write_record_carrying+OFF>
	mov    %rbx,%rdi
	call   <.Lswitch.table._ZN9inf_store7catalog9NsCatalog6encode17hb15ce09b8ccb2dc1E+OFF>



