#!/usr/bin/env python3
"""Render an inf-compare campaign report into the website's evidence page.

Like gen-compat-page.py, this keeps the site incapable of drifting from the
artifact (law L10): the page is generated verbatim from the committed
report.md of a comparative campaign — never hand-written.

Hard rule: the generator REFUSES any report whose tier banner is not
"reference-box (binding, citation-grade)". Dev-tier reports cannot become
public pages, by construction. The output lives under site/evidence/, which
scripts/check-ledger-copy.py deliberately skips: these pages ARE the
artifacts the ledger rows cite (the copy gate reviews prose, not evidence).

Usage:
    python3 scripts/gen-compare-page.py \
        --report ../.artifacts/compare/<ts>-compare/report.md \
        --out site/evidence/inf-compare.html \
        --ledger-rows "C5, C7" \
        --campaign "M2.5-S19 closure campaign, 2026-07-10"

stdlib only.
"""

import argparse
import html
import re
import sys
from pathlib import Path

BINDING_BANNER = "reference-box (binding, citation-grade)"

PAGE_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — InfinityDB Evidence</title>
<meta name="description" content="Verbatim render of a binding inf-compare campaign report: competitors in the same run on the same box, environment recorded, raw artifacts committed.">
<link rel="icon" href="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2034%2018'%3E%3Ccircle%20cx='10'%20cy='9'%20r='7'%20fill='none'%20stroke='%237c5cff'%20stroke-width='2.4'/%3E%3Ccircle%20cx='24'%20cy='9'%20r='7'%20fill='none'%20stroke='%233ee6c4'%20stroke-width='2.4'/%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/site.css">
<style>
.evidence-wrap {{ max-width: var(--container); margin: 0 auto; padding: 64px var(--pad-x) 120px; animation: fadeUp 0.4s both; }}
.evidence-wrap h2 {{ font-size: 22px; margin: var(--sp-5) 0 8px; }}
.evidence-wrap p {{ font-size: 14px; line-height: 1.7; color: var(--text-muted); max-width: 760px; }}
.evidence-wrap ul {{ color: var(--text-muted); font-size: 13.5px; line-height: 1.8; max-width: 760px; }}
.tier-banner {{
  display: inline-block; font: 700 11px/1 var(--mono); letter-spacing: 0.12em;
  color: var(--bg); background: var(--teal); border-radius: 99px; padding: 6px 14px;
  text-transform: uppercase;
}}
table.data td:first-child {{ color: var(--teal); }}
table.data td {{ font-family: var(--mono); font-size: 12.5px; }}
.gen-note {{ font: 400 10.5px/1.9 var(--mono); letter-spacing: 0.06em; color: var(--text-faint); margin-top: var(--sp-5); }}
</style>
</head>
<body>

<nav class="nav">
  <div class="nav-inner">
    <a href="../index.html" class="nav-brand">
      <svg class="logo" width="34" height="18" viewBox="0 0 34 18" aria-hidden="true">
        <circle cx="10" cy="9" r="7" fill="none" stroke="#7c5cff" stroke-width="2.4"/>
        <circle cx="24" cy="9" r="7" fill="none" stroke="#3ee6c4" stroke-width="2.4"/>
      </svg>
      <span class="mark">infinity<b>DB</b></span>
      <span class="nav-badge neutral">EVIDENCE</span>
    </a>
    <span class="nav-spacer"></span>
    <button class="nav-toggle" aria-label="Toggle navigation" aria-expanded="false">&#9776;</button>
    <div class="nav-links">
      <a href="../index.html">HOME</a>
      <a href="../docs/index.html">DOCS</a>
      <a href="../docs/benchmarks.html">BENCHMARKS</a>
      <a class="nav-cta" href="https://github.com/">&#9733; GITHUB</a>
    </div>
  </div>
</nav>

<main class="evidence-wrap">
  <p class="doc-kicker">Evidence &middot; generated page &mdash; do not edit</p>
  <h1 class="page-title">{title}</h1>
  <p><span class="tier-banner">{tier}</span></p>
  <div class="callout">
    <span class="callout-tag"><strong>What this page is:</strong></span>
    a verbatim render of the committed report from {campaign} &mdash; the
    comparative campaign behind ledger rows {ledger_rows}. Every engine ran
    in the same run on the same box with its launch command recorded below;
    the environment check (governor, EPP, turbo, thermals, clean tree)
    passed before any row was recorded. Numbers here are quotable only in
    the wording the claim ledger allows &mdash; see
    <a href="../docs/benchmarks.html">how we benchmark</a> for the rules,
    including the independent-generator cross-check that deliberately flags
    its own divergences below.
  </div>
"""

PAGE_FOOT = """  <p class="gen-note">GENERATED BY scripts/gen-compare-page.py FROM {src} &mdash; REGENERATED PER CAMPAIGN; HAND EDITS ARE OVERWRITTEN &middot; RAW GENERATOR OUTPUT (memtier JSON, redis-benchmark CSV) IS COMMITTED UNDER THE SAME ARTIFACT DIRECTORY</p>
</main>

<footer class="footer">
  <div class="footer-inner">
    <span class="mark">&copy; 2026 INFINITYDB &mdash; APACHE 2.0 &middot; RUST &middot; <b>infinityd</b></span>
    <div class="footer-links">
      <a href="../docs/index.html">DOCS</a>
      <a href="../blog/index.html">BLOG</a>
      <a href="../docs/roadmap.html">ROADMAP</a>
      <a href="https://github.com/">GITHUB &#8599;</a>
    </div>
  </div>
</footer>

<script>
(function () {{
  var t = document.querySelector('.nav-toggle');
  var l = document.querySelector('.nav-links');
  if (t && l) t.addEventListener('click', function () {{
    var open = l.classList.toggle('open');
    t.setAttribute('aria-expanded', open ? 'true' : 'false');
  }});
}})();
</script>
</body>
</html>
"""


def md_inline(text: str) -> str:
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    return out


def render_table(rows):
    head, sep, body = rows[0], rows[1], rows[2:]
    aligns = ["right" if c.strip().endswith(":") else "left"
              for c in sep.strip("|").split("|")]

    def cells(line, tag):
        out = []
        for i, c in enumerate(line.strip().strip("|").split("|")):
            a = aligns[i] if i < len(aligns) else "left"
            style = ' style="text-align:right"' if a == "right" else ""
            out.append(f"<{tag}{style}>{md_inline(c.strip())}</{tag}>")
        return "".join(out)

    h = f"<tr>{cells(head, 'th')}</tr>"
    b = "\n".join(f"<tr>{cells(r, 'td')}</tr>" for r in body if r.strip())
    return f'<div class="table-wrap"><table class="data"><thead>{h}</thead><tbody>\n{b}\n</tbody></table></div>'


def render_body(md: str) -> str:
    lines = md.splitlines()
    out, i = [], 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("# ") or line.startswith("> **Tier:**"):
            i += 1  # title + tier rendered by the shell
            continue
        if line.startswith("## "):
            out.append(f"<h2>{md_inline(line[3:].strip())}</h2>")
            i += 1
            continue
        if line.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].startswith("|"):
                rows.append(lines[i])
                i += 1
            if len(rows) >= 2:
                out.append(render_table(rows))
            continue
        if line.startswith("- "):
            items = []
            while i < len(lines) and lines[i].startswith("- "):
                items.append(f"<li>{md_inline(lines[i][2:].strip())}</li>")
                i += 1
            out.append("<ul>\n" + "\n".join(items) + "\n</ul>")
            continue
        if line.strip():
            out.append(f"<p>{md_inline(line.strip())}</p>")
        i += 1
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="Render a binding inf-compare report as the site's evidence page.")
    ap.add_argument("--report", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--ledger-rows", required=True, help='e.g. "C5, C7"')
    ap.add_argument("--campaign", required=True, help='e.g. "the M2.5-S19 closure campaign (2026-07-10)"')
    args = ap.parse_args()

    src = Path(args.report)
    md = src.read_text(encoding="utf-8")

    tier_m = re.search(r"^> \*\*Tier:\*\*\s*(.+)$", md, re.M)
    tier = tier_m.group(1).strip() if tier_m else "(no tier banner)"
    if tier != BINDING_BANNER:
        sys.exit(f"REFUSED: report tier is '{tier}', not '{BINDING_BANNER}' — "
                 "dev-tier reports cannot become public evidence pages (L10/§19).")

    title_m = re.search(r"^# (.+)$", md, re.M)
    title = title_m.group(1).strip() if title_m else "inf-compare report"

    page = (PAGE_HEAD.format(title=html.escape(title), tier=html.escape(tier),
                             campaign=html.escape(args.campaign),
                             ledger_rows=html.escape(args.ledger_rows))
            + render_body(md)
            + PAGE_FOOT.format(src=html.escape(str(src))))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page, encoding="utf-8")
    print(f"wrote {out} from {src} (tier: {tier})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
